### ISSUE TITLE
I fogot to back up the .exe

### ISSUE THREAD

**Issue by salvador-blanco** [xyos420/mw3#1]
Unfortunately, the trick didn't work for me.
And unfortunately, I forgot to back up the original .exe when following the instructions 
Do you have a back up of that file?

Thank you!!

**Comment by xyos420** [comment]
just click rightclick on the Game in Steam Libary -> Properties -> Local Files -> Veriefy Game blablabla
then Steam should download the new .exe, if it's not working try to delte the .exe i've provided you and redo the Steps.

I think i wrote you in Steam aswell i can show you that it's working like it should if you wan't to.
